### ISSUE TITLE
paredit-kill is missing

### ISSUE THREAD

**Issue by pbiggar** [jonspalding/lisp-paredit#23]
In emacs, ctrl-k is mapped to paredit-kill, which kills until the end of the current sexp. This is missing from lisp-paredit, and I am stuck with kill-line, which is so very different :(

**Comment by pbiggar** [comment]
If I had to guess, lisp-paredit:kill-sexp-forwards is supposed to be paredit-kill. It does some of what paredit-kill does, but it looks like it only deletes the word in front of it when in a sexp, it doesn't delete til the end of the sexp. Looking at the code, this is likely upstream, so I'll report it to paredit.js.

**Comment by pbiggar** [comment]
Actually, it's not upstream (upstream issue fyi: https://github.com/rksm/paredit.js/issues/11).

It's because the `count` argument to killSexp is provided. I've verified that it works if that's omitted.

The count was added [here](https://github.com/jonspalding/lisp-paredit/blob/44406c15d43826e04309b02c12be5ac5396051b0/lib/edit-commands.coffee#L196), in 2ba4297c, as part of fixing #7. Not sure why.

**Comment by neil-lindquist** [comment]
I added a kill to end of sexp command (and kill to start of sexp) to the master branch.  For the default keymap, I deviated from emac's ctrl-k because Atom prefixes some default commands with ctrl-k.  I currently have the default as alt-shift-delete and cmd-shift-delete to match the commands to kill a single sexp.  A custom keymap should be easy enough for people who prefer emacs keybindings.

So, I'm going to close this unless there is disagreement on the default keystrokes.
