### ISSUE TITLE
HTMLDocument.registerElement is deprecated.

### ISSUE THREAD

**Issue by josharmenta** [jonspalding/lisp-paredit#44]
Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements
```
HTMLDocument.registerElement (file:///Applications/Pulsar.app/Contents/Resources/app.asar/static/index.js:99:12)
registerElement (/Users/joshuaarmenta/.pulsar/packages/lisp-paredit/node_modules/space-pen/lib/space-pen.js:66:88)
Builder.openTag (/Users/joshuaarmenta/.pulsar/packages/lisp-paredit/node_modules/space-pen/lib/space-pen.js:297:27)
Builder.tag (/Users/joshuaarmenta/.pulsar/packages/lisp-paredit/node_modules/space-pen/lib/space-pen.js:274:12)
Function.div (/Users/joshuaarmenta/.pulsar/packages/lisp-paredit/node_modules/space-pen/lib/space-pen.js:83:49)
Function.content (/Users/joshuaarmenta/.pulsar/packages/lisp-paredit/lib/status-bar-view.coffee:16:19)
```

**Comment by neil-lindquist** [comment]
Unfortunately, lisp-paredit doesn't use `document.registerElement` directly, but through the atom-space-pen-views library that the UI is built with.  And the atom-space-pen-views repo has been frozen with the sunset of Atom.

So, I'll need to switch to a different UI library (probably etch, since that's what I replaced space-pens with in SLIMA).

**Comment by neil-lindquist** [comment]
I just released the new etch status bar.  So, you shouldn't be seeing this warning anymore.
