### ISSUE TITLE
Line endings are not taken from current context

### ISSUE THREAD

**Issue by krzysztofpniak** [jonspalding/lisp-paredit#7]
If you run it on windows default line ending of editor is CRLF. At the moment LF is always pasted as line end. So it is impossible to use it until you switch manually line endings in Atom.

**Comment by jonspalding** [comment]
Released in 0.5.0. Can you check it's ok as I'm not on Windows?

**Comment by krzysztofpniak** [comment]
Unfortunately it is not working, after I press enter in CRLF mode new line is added, but cursor goes at the beginning of the line on which enter was pressed. Additionaly indent is missing in CRLF mode before second line.

before:
(if |(println "asd))

after:
|(if
(println "asd))

**Comment by jonspalding** [comment]
Ok, I think I can replicate by manually setting the file to CRLF.

**Comment by alza-bitz** [comment]
Hi,

I'm still seeing what appears to be this issue with 0.6.0, on Windows.. When I switch line endings in Atom to CRLF as a workaround, pressing enter does give me newlines but bizarrely the cursor stays on the first line added instead of with each new line added!

In any case, I'd prefer to stick to LF line endings for my files, and when I use this mode I still get the odd behaviour described above (pressing enter puts the cursor at the beginning of the line, and further presses give newlines above the cursor).

Please could this issue be re-opened and investigated? It makes paredit difficult to use on Windows :/

Thanks!
